### ISSUE TITLE
Отсутствуют файлы проекта

### ISSUE THREAD

**Issue by turinkay** [hohomonix23274/Monitorexe#1]
При выкладывании исходных кодов проекта на гитхаб нужно прикладывать и файлы проекта. Мне вот пришлось создать в вижуал студии новый проект, скопировать туда исходники и только тогда я смог его собрать. А в идеале я должен был бы просто скачать проект, открыть его и собрать, без лишних телодвижений.

**Comment by hohomonix23274** [comment]
Убрал gitignore
