### ISSUE TITLE
Включение лишнего заголовочного файла мешает сборке

### ISSUE THREAD

**Issue by turinkay** [hohomonix23274/Monitorexe#2]
Предлагаю разобраться, зачем нужен `#include "pch.h"` Тут следовало бы его убрать совсем. Если бы проект выложен был бы как проект вижуал студии , то это было бы менее критично, потому что оно бы тогда не помешало бы сборке.

**Comment by hohomonix23274** [comment]
Про #include "pch.h" помню, что еще обсуждали на очной встрече. Его можно убрать через свойства процесса, что я и сделал.
