### ISSUE TITLE
Проверка наличия доступа к процессу

### ISSUE THREAD

**Issue by turinkay** [hohomonix23274/Monitorexe#3]
Вот в этой строке https://github.com/hohomonix23274/Monitorexe/blob/dbac72cdf84e4b457429bb3f3fc43acc962b9c82/monitor/monitor/monitor.cpp#L39
при получении hHandle обязательно надо проверить, что он ненулевой. Возможно, мы не можем получить доступ к процессу, или его нет.

**Comment by hohomonix23274** [comment]
Добавил цикл который проверяет, что процесс не нулевой, ну и так же выводит - "Нет доступа", если ввести некоретный id ( например: 999999999).
