### ISSUE TITLE
Некорректная проверка работоспособности программы

### ISSUE THREAD

**Issue by turinkay** [hohomonix23274/Monitorexe#5]
Вот этот 
https://github.com/hohomonix23274/Monitorexe/blob/dbac72cdf84e4b457429bb3f3fc43acc962b9c82/monitor/monitor/monitor.cpp#L84
явно установлен, чтобы не выводить большое количество информации обо всей виртуальной памяти процесса и вывести информацию только об одной странице. Это в корне неправильно, тем более, что в таком случае мы только проверяем статус страницы по адресу 0x00000000 (предлагаю подумать о том, почему это может быть неправильно). На самом деле нужно выводить только информацию о тех страницах, которые нам интересны (R, RX, RW, RWX). Для этого нужно реорганизовать код функции и разделить логику работы и печать результата, тогда станет возможным выводить только информацию об интересующих нас страницах. Я убрал этот break у себя и среди вывода программы есть информация о страницах R/RW/..., что свидетельствует о том, что остальное написано правильно.

**Comment by hohomonix23274** [comment]
Сделал, теперь выдает только 4 типа страница с правами доступа (R/RX...).
