### ISSUE TITLE
Проблемы с разрядностью

### ISSUE THREAD

**Issue by turinkay** [hohomonix23274/Monitorexe#6]
Используемая структура `PROCESSENTRY32` может при сборке на разных разрядностях иметь разный тип поля `szExeFile`. В коде, например, вот здесь
https://github.com/hohomonix23274/Monitorexe/blob/dbac72cdf84e4b457429bb3f3fc43acc962b9c82/monitor/monitor/monitor.cpp#L24
явно предполагается, что тип поля CHAR. А вот у меня тип этого поля оказался WCHAR (потому что у меня в windows.h определено вот так: `#define PROCESSENTRY32 PROCESSENTRY32W`), поэтому я получаю при выводе что-то такое:
![image](https://user-images.githubusercontent.com/11706952/51786837-324b4b00-217b-11e9-981c-a3e4d80510c4.png)

**Comment by hohomonix23274** [comment]
Самым простым выходом из ситуации увидел использовать вместо UNICODE - Multibyte Character Set, что позволяет без лишних телодвижений ( как я понял, пришлось бы полностью переписывать код, чтобы можно было WCHAR использовать) решить проблему.
